#!/bin/bash

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

source ${SCRIPT_DIR}/env-avr.sh

Options=$@
while [[ $# > 0 ]] ; do
  case "$1" in
    -P)
      Port="$2"
      shift
      ;;
    *)
      # skip
      ;;
  esac
  shift
done

docker run --rm -t -u root --device=${Port} ${VOLUMES} ${CONTAINER} avrdude ${Options}

